BaaN/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accountapp.views import AccountMainView

urlpatterns = [
    path('', AccountMainView.as_view(), name="home"),
    path('summernote/', include('django_summernote.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('bookmarks/', include('bookmarkapp.urls')),
    path('calendars/', include('calendarapp.urls')),
    path('memos/', include('memoapp.urls')),
    path('todos/', include('todoapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

memoapp/urls.py
from django.conf.urls import url
from django.urls import path

from memoapp import views
from memoapp.views import MemoListView, MemoCreateView, MemoDetailView

app_name = 'memoapp'

urlpatterns = [
    path('list/', MemoListView.as_view(), name='list'),
    # path('create/', views.memo_create, name='create'),
    path('create/', MemoCreateView.as_view(), name='create'),
    path('detail/<int:pk>', MemoDetailView.as_view(), name='detail'),
    # path('update/<int:pk>', MemoUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.memo_delete, name='delete'),
]

todoapp/urls.py
from django.urls import path

from todoapp import views
from todoapp.views import TodoListView, TodoCreateView

app_name = 'todoapp'

urlpatterns = [
    path('list/', TodoListView.as_view(), name='list'),
    path('create/', TodoCreateView.as_view(), name='create'),
    path('update/<int:pk>', views.todo_update, name='update'),
    path('delete/<int:pk>', views.todo_delete, name='delete'),
    path('check/<int:pk>', views.todo_check, name='check'),
    path('delete_all/', views.todo_delete_all, name='delete_all'),
]

memoapp/models.py
from django.contrib.auth.models import User
from django.db import models


class Memo(models.Model):
    title = models.CharField(max_length=10, null=True)
    content = models.TextField()
    created_at = models.DateField(auto_now=True)

memoapp/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget

from memoapp.models import Memo


class MemoForm(forms.ModelForm):
    class Meta:
        model = Memo
        fields = ['title', 'content']
        widgets = {
            'content' : SummernoteWidget(),
        }

# class MultipleForm(forms.Form):
#     action = forms.CharField(max_length=60, widget=forms.HiddenInput())
#
#
# class CreateForm(MultipleForm):
#     title = forms.CharField(max_length=10, null=True)
#     content = forms.TextField()
#     created_at = forms.DateField(auto_now=True)
#
# class UpdateForm(MultipleForm):
#     title = forms.CharField(max_length=10, null=True)
#     content = forms.TextField()
#     created_at = forms.DateField(auto_now=True)

memoapp/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, ListView, UpdateView, CreateView
from django.views.generic.edit import FormMixin

from memoapp.forms import MemoForm
from memoapp.models import Memo

# def memo_create(request):
#     form = MemoForm(request.POST)
#     if form.is_valid():
#         title = request.POST.get('title')
#         content = request.POST.get('content')
#         user = request.user
#         return redirect("home")
#     return render(request, "memoapp/create.html", {"form": form})


@method_decorator(login_required(login_url='/accounts/login/'), 'get')
@method_decorator(login_required(login_url='/accounts/login/'), 'post')
class MemoCreateView(CreateView):
    model = Memo
    form_class = MemoForm
    template_name = 'memoapp/create.html'

    def form_valid(self, form):
        temp_memo = form.save(commit=False)
        temp_memo.user = self.request.user
        temp_memo.save()
        return super().form_valid(form)

    def get_success_url(self):
        # return reverse('memoapp:list', kwargs={'pk':self.object.pk})
        # return HttpResponseRedirect(reverse('memoapp:list'))
        return reverse('home')


@method_decorator(login_required(login_url='/accounts/login/'), 'get')
class MemoListView(ListView, FormMixin):
    model = Memo
    form_class = MemoForm
    context_object_name = 'memo_list'
    template_name = 'memoapp/list.html'
    paginate_by = 5


@method_decorator(login_required(login_url='/accounts/login/'), 'get')
class MemoDetailView(DetailView, FormMixin):
    model = Memo
    form_class = MemoForm
    context_object_name = 'target_memo'

    def get_success_url(self):
        return reverse('memoapp:list')


# @method_decorator(login_required(login_url='/accounts/login/'), 'get')
# class MemoUpdateView(UpdateView, FormMixin):
#     model = Memo
#     context_object_name = 'target_memo'
#     form_class = MemoForm
#
#     def get_success_url(self):
#         return reverse('memoapp:list')

@login_required(login_url='/accounts/login/')
def memo_delete(request, pk):
    memo = Memo.objects.get(pk=pk)
    memo.delete()
    return HttpResponseRedirect(reverse('memoapp:list'))

memoapp/templates/memoapp/create.html
{% load bootstrap4 %}

{% block content %}

    <div id="memo_add" class="modal fade modal_box_div" role="dialog" data-backdrop="false">
        <div class="modal-dialog modal-dialog-centered" role="document">

            <h4>add new memo</h4>
            <hr>

            <form action="{% url 'memoapp:create' %}" method="post" class="form-inline">
                {% csrf_token %}
                <table>
                    {{form.as_table}}
                </table>
                <button type="submit" class="button_add material-icons">add</button>
                <button type="button" class="button_add material-icons" data-dismiss="modal">cancel</button>
            </form>
        </div>
    </div>

    <button type="button" class="material-icons button_add" data-target="#memo_add" data-toggle="modal">add</button>

{% endblock %}

memoapp/templates/memoapp/list.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}


    <div class="bookmark_form_div">
        <h2 class="form_title" style="margin-bottom: 1rem;">Memo list&nbsp</h2>
        <hr>

        {% for memo in memo_list %}
        <div>
            <a data-toggle="modal" data-target="#memo_detail{{ memo.pk }}">{{ memo.title | safe }}</a>
            <button class="material-icons" data-toggle="modal" data-target="#memo_update{{ memo.pk }}" class="material-icons">edit</button>
            <button class="material-icons" data-toggle="modal" data-target="#delete_modal{{ memo.pk }}" class="material-icons">delete</button>


        </div>

        <div id="delete_modal{{ memo.pk }}" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">delete memo</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>Are you sure you want to delete this memo?</p>
                    </div>
                    <div class="modal-footer">
                        <button onclick="delete_modal({{ memo.pk }})" type="button" class="btn btn-dark">delete</button>
                        <button type="button" class="btn btn-light" data-dismiss="modal">cancel</button>
                    </div>
                </div>
            </div>
        </div>

        <div id="memo_detail{{ memo.pk }}" class="modal fade modal_box_div" role="dialog" data-backdrop="false">
              <div class="modal-dialog modal-dialog-centered" role="document">
                  <div>
                    title : {{ memo.title }}
                  </div>
                  <div>
                    content : {{ memo.content | safe }}
                  </div>
                  <hr>
                  <button type="button" class="btn btn-default" data-dismiss="modal">cancel</button>
              </div>
        </div>

        {% endfor %}

    </div>

    {% include 'snippets/pagination.html' with page_obj=page_obj %}

    <hr>

    {% include 'memoapp/create.html' %}

    <script type="text/javascript">
        function delete_modal( pk ) {
            location.replace('/memos/delete/'+pk);

        function hideModal( id ) {
            $(id).removeClass("in");
            $(".modal-backdrop").remove();
            $(".show").remove();
            $('body').removeClass('modal-open');
            $('body').css('padding-right', '');
            $(id).hide();
        }
    </script>

{% endblock %}

memoapp/templates/memoapp/list2.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <head>
        <title></title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-lite.css"/>
    </head>

    <div>
        <h2>Summernotes</h2>
        <hr>

        {% for memo in memo_list %}
        <div style="width:20rem; height:10rem; background-color: pink; border-radius: 1rem;">
            <button data-toggle="modal" data-target="#MemoDetailView">{{ memo.title | safe }}</button>
            <button class="material-icons" data-toggle="modal" data-target="#delete_modal" class="material-icons">delete</button>
            <button class="material-icons" data-toggle="modal" data-target="#MemoUpdateView" class="material-icons">edit</button>
        </div>

        <div id="delete_modal" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">delete memo</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>Are you sure you want to delete this memo?</p>
                    </div>
                    <div class="modal-footer">
                        <button onclick="delete_modal({{ memo.pk }})" type="button" class="btn btn-dark">delete</button>
                        <button type="button" class="btn btn-light" data-dismiss="modal">cancel</button>
                    </div>
                </div>
            </div>
        </div>

          <div id="MemoDetailView" class="modal fade" role="dialog" data-backdrop="false"
               style="background-color: white; width: 50%; height: 50%; text-align: center; margin: auto auto; border: 1px solid gray;">
              <div class="modal-dialog modal-dialog-centered" role="document">

                  <h4>Detailed memo</h4>
                  <hr>

                  <form action="{% url 'memoapp:detail' pk=target_memo.pk %}" method="post" class="form-inline">
                      <div>
                        title : {{ target_memo.title }}
                      </div>
                      <div>
                        content : {{ target_memo.content | safe }}
                      </div>
                      <hr>
                      <button type="button" class="btn btn-default" data-dismiss="modal">cancel</button>
                  </form>
              </div>
          </div>


        {% endfor %}

        <hr>

        {% include 'memoapp/create.html' %}
    </div>
    {% include 'snippets/pagination.html' with page_obj=page_obj %}



    <script type="text/javascript">
        function delete_modal( pk ) {
            location.replace('/memos/delete/'+pk);
        }
    </script>

{% endblock %}

memoapp/templates/memoapp/update.html
{% extends 'base.html' %}

{% load bootstrap4 %}
{% block content %}
  <div>
    <div>
      <h4>Memo Update</h4>
    </div>
    <form action="{% url 'memoapp:update' pk=target_memo.pk %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <table>
        {{form.as_table}}
      </table>
      <input type="submit" class = "btn btn-dark rounded-pill col-6 mt-3">
    </form>
  </div>
{% endblock %}