BaaN/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accountapp.views import AccountMainView

urlpatterns = [
    path('', AccountMainView.as_view(), name="home"),
    path('summernote/', include('django_summernote.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('bookmarks/', include('bookmarkapp.urls')),
    path('calendars/', include('calendarapp.urls')),
    path('memos/', include('memoapp.urls')),
    path('todos/', include('todoapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp import views
from accountapp.views import AccountCreateView, AccountDeleteView, AccountMainView, AccountLoginView

app_name = 'accountapp'


urlpatterns = [
    path('main/', AccountMainView.as_view(), name='main'),  ### 임시 메인 페이지 경로

    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
    path('search/', views.search, name='search'),
]

bookmarkapp/urls.py
from django.conf.urls import url
from django.contrib.auth import admin
from django.urls import path

from bookmarkapp import views
from bookmarkapp.views import BookmarkListView, bookmark_delete

app_name = 'bookmarkapp'

urlpatterns = [
    path('list/', BookmarkListView.as_view(template_name='bookmarkapp/list.html'), name='list'),
    path('create/', views.bookmark_create, name='create'),
    path('delete/<int:pk>', views.bookmark_delete, name='delete'),
    path('update/<int:pk>', views.bookmark_update, name='update'),
]

calendarapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name = 'calendarapp'

urlpatterns = [
path('main/', TemplateView.as_view(template_name='calendarapp/main.html'), name='main')
]

memoapp/urls.py
from django.conf.urls import url
from django.urls import path

from memoapp import views
from memoapp.views import MemoListView, MemoCreateView, MemoDetailView

app_name = 'memoapp'

urlpatterns = [
    path('list/', MemoListView.as_view(), name='list'),
    # path('create/', views.memo_create, name='create'),
    path('create/', MemoCreateView.as_view(), name='create'),
    path('detail/<int:pk>', MemoDetailView.as_view(), name='detail'),
    # path('update/<int:pk>', MemoUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.memo_delete, name='delete'),
]

todoapp/urls.py
from django.urls import path

from todoapp import views
from todoapp.views import TodoListView, TodoCreateView

app_name = 'todoapp'

urlpatterns = [
    path('list/', TodoListView.as_view(), name='list'),
    path('create/', TodoCreateView.as_view(), name='create'),
    path('update/<int:pk>', views.todo_update, name='update'),
    path('delete/<int:pk>', views.todo_delete, name='delete'),
    path('check/<int:pk>', views.todo_check, name='check'),
    path('delete_all/', views.todo_delete_all, name='delete_all'),
]

accountapp/models.py
from django.db import models

accountapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class AccountCreationForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={
            "placeholder": "enter your id",
            "class": "account_form_input",
        })
    )

    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(attrs={
            "placeholder": "enter your password",
            "class": "account_form_input",
        })
    )

    password2 = forms.CharField(
        label="Password Confirm",
        widget=forms.PasswordInput(attrs={
            "placeholder": "confirm password",
            "class": "account_form_input",
        })
    )

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', ]


class AccountLoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={
            "placeholder": "enter your id",
            "class": "account_form_input",
        })
    )

    password = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(attrs={
            "placeholder": "enter your password",
            "class": "account_form_input",
        })
    )

    def __init__(self, request=None, *args, **kwargs):
        super(AccountLoginForm, self).__init__(*args, **kwargs)  # 꼭 있어야 한다!

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# Create your models here.
from django.contrib.auth.views import LoginView
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import CreateView, DeleteView, DetailView, UpdateView, RedirectView, ListView

from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountCreationForm, AccountLoginForm

has_ownership = [account_ownership_required, login_required(login_url='/accounts/login/')]


# BaaN 메인 페이지
@method_decorator(login_required(login_url='/accounts/login/'), 'get')
class AccountMainView(ListView):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/index.html'


########################################


class AccountCreateView(CreateView):
    model = User
    form_class = AccountCreationForm
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/create.html'


class AccountLoginView(LoginView):
    template_name = 'accountapp/login.html'
    form_class = AccountLoginForm


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'


def search(request):
    engine = request.GET.get('engine')
    query = request.GET.get('query')
    query = query.replace(' ', '+')

    if engine == 'google':
        url = "https://www.google.com/search?q="
    elif engine == 'naver':
        url = "https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query="
    else:
        url = "https://www.youtube.com/results?search_query="

    url += query
    return HttpResponseRedirect(url)

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div class="account_form_div">
        <div>
            <h3 class="form_title"><strong>Sign Up</strong></h3>
            <hr>
        </div>
        <form action="{% url 'accountapp:create' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="button_submit" value="start"><br>
            <a href="{% url 'accountapp:login' %}" class="account_url">login page</a>
        </form>
    </div>
{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div>
    <div class="">
        <div>
            <h3><strong>Quit</strong></h3>
            <hr>
        </div>
        <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
            {% csrf_token %}
            <p>⚠️ 회원 탈퇴는 곧바로 진행됩니다. 주의하세요! </p>
            <input type="submit" value="quit" class="btn btn-danger">
        </form>
    </div>
</div>

{% endblock %}

accountapp/templates/accountapp/index.html
{% include 'base.html' %}
<script src='/static/main_ajax_scripts.js'></script>

<script type="text/javascript">
    $(document).ready(function() {
        load_bookmark();
        load_todo();
        load_memo();
    });
</script>

<body>
    <header class="header">
            <div class="logo">
                <a href="{% url 'home' %}" class="home_link">BaaN</a>
            </div>
            <div class="search">
                <form method="get" action="{% url 'accountapp:search' %}" class="search_form">
                    <select name="engine" id="engine">
                        <option value="google">google ▼</option>
                        <option value="naver">naver</option>
                        <option value="youtube">youtube</option>
                    </select>
                    <input type="text" name="query" placeholder="search for..." class="search_input">
                    <input style="font-size: 2.4rem; vertical-align: bottom;" type="submit" class="search_button material-icons" value="search">
                </form>
            </div>
            <div class="gnb">
                {% if user.is_authenticated %}
                    {{ user.username }}
                    <a href="{% url 'accountapp:logout' %}" class="material-icons" style="font-size: 1rem;">logout</a>
                {% endif %}
            </div>
    </header>

    <div class="main" >
        <div >
            <div class="link_flex_box">
                <div id="bookmark">
                </div>
                <div id="todo">
                    <a href="{% url 'todoapp:list' %}">todo</a>
                </div>
                <div id="memo">
                    <a href="{% url 'memoapp:list' %}">memo</a>
                </div>
                <div class="link_box">
                    <a href="{% url 'calendarapp:main' %}">calendar</a>
                </div>
                <div class="link_box">
                    <a href="">weather</a>
                </div>
            </div>
        </div>
    </div>
</body>

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div>
    <div class="account_form_div">
        <div>
            <h3 class="form_title"><strong>Login</strong></h3>
            <hr>
        </div>
        <form action="" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" value="login" class="button_submit">
            <a href="{% url 'accountapp:create' %}" class="account_url"><h6>SignUp</h6></a>
        </form>
    </div>
</div>
{% endblock %}

accountapp/templates/accountapp/main.html
{% include 'base.html' %}

<body>
    <header class="header">
            <div class="logo">
                <a href="{% url 'home' %}" class="home_link">BaaN</a>
            </div>
            <div class="search">
                <form method="get" action="{% url 'accountapp:search' %}" class="search_form">
                    <select name="engine" id="engine">
                        <option value="google">google</option>
                        <option value="naver">naver</option>
                        <option value="youtube">youtube</option>
                    </select>
                    <input type="text" name="query" class="search_input">
                    <input style="font-size: 2.4rem; padding: 0; vertical-align: bottom;" type="submit" class="search_button material-icons" value="search">
                </form>
            </div>
            <div class="gnb">
                {% if user.is_authenticated %}
                    {{ user.username }}
                    <a href="{% url 'accountapp:logout' %}" class="material-icons" style="font-size: 1rem;">logout</a>
                {% endif %}
            </div>
    </header>

{#밑 내용#}
    <div class="main" >
        <div >
            <div class="link_flex_box">
                <div class="link_box">
                    <a href="{% url 'bookmarkapp:list' %}">bookmark</a>
                </div>
                <div class="link_box">
                    <a href="{% url 'todoapp:list' %}">todo</a>
                </div>
                <div class="link_box">
                    <a href="{% url 'memoapp:list' %}">memo</a>
                </div>
                <div class="link_box">
                    <a href="{% url 'calendarapp:main' %}">calendar</a>
                </div>
                <div class="link_box">
                    <a href="">weather</a>
                </div>
            </div>
        </div>
    </div>



</body>
</html>