BaaN/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accountapp.views import AccountMainView

urlpatterns = [
    path('', AccountMainView.as_view(), name="home"),
    path('summernote/', include('django_summernote.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('bookmarks/', include('bookmarkapp.urls')),
    path('calendars/', include('calendarapp.urls')),
    path('memos/', include('memoapp.urls')),
    path('todos/', include('todoapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookmarkapp/urls.py
from django.conf.urls import url
from django.contrib.auth import admin
from django.urls import path

from bookmarkapp import views
from bookmarkapp.views import BookmarkListView, bookmark_delete

app_name = 'bookmarkapp'

urlpatterns = [
    path('list/', BookmarkListView.as_view(template_name='bookmarkapp/list.html'), name='list'),
    path('create/', views.bookmark_create, name='create'),
    path('delete/<int:pk>', views.bookmark_delete, name='delete'),
    path('update/<int:pk>', views.bookmark_update, name='update'),
]

bookmarkapp/models.py
# Create your models here.
from django.contrib.auth.models import User
from django.db import models

# url -> 이미지 변경을 위한 모듈들
# from urllib.parse import urlparse
# from django.core.files import File
# from utils.file import download, get_buffer_ext


class Bookmark(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='bookmark', null=True)
    title = models.CharField(max_length=100, blank=True, null=True)
    favicon_url = models.URLField("favicon_url", blank=True)
    url = models.URLField("url")

    def __str__(self):
        return self.url
    #
    # def save(self, *args, **kwargs):
    #     # ImageField에 파일이 없고, url이 존재하는 경우에만 실행
    #     if self.favicon_url and not self.thumbnail:
    #         thumbnail_url = self.favicon_url
    #
    #         if thumbnail_url:
    #             temp_file = download(thumbnail_url)
    #             file_name = '{favicon_url}_{urlparse}.{ext}'.format(
    #                 favicon_url=self.favicon_url,
    #                 # url의 마지막 '/' 내용 중 확장자 제거
    #                 # ex) url = 'https://~~~~~~/bag-1623898_960_720.jpg'
    #                 #     -> 'bag-1623898_960_720.jpg'
    #                 #     -> 'bag-1623898_960_720'
    #                 urlparse=urlparse(thumbnail_url).path.split('/')[-1].split('.')[0],
    #                 ext=get_buffer_ext(temp_file)
    #             )
    #             self.thumbnail.save(file_name, File(temp_file))
    #             super().save()
    #
    #     else:
    #         super().save()

bookmarkapp/forms.py
from django import forms
from django.forms import ModelForm
from bookmarkapp.models import Bookmark


class BookmarkCreationForm(ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'editable text-left',
                                                           'style': 'height: auto;'}))

    class Meta:
        model = Bookmark
        fields = ['title', 'url']

bookmarkapp/views.py
# from django.shortcuts import render
import ssl

from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.http import HttpResponseRedirect, request
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import ListView, UpdateView, DeleteView

from accountapp.decorators import account_ownership_required
from bookmarkapp.models import Bookmark

# 북마크에서 사용할 title을 가져오기 위한 크롤링 모듈
from urllib.request import urlopen
from bs4 import BeautifulSoup
from django.core.validators import URLValidator

has_ownership = [account_ownership_required, login_required(login_url='/accounts/login/')]


@method_decorator(login_required(login_url='/accounts/login/'), 'get')
class BookmarkListView(ListView):
    model = Bookmark
    context_object_name = 'bookmark_list'
    template_name = 'bookmarkapp/list.html'

    def get_context_data(self, **kwargs):
        object_list = Bookmark.objects.filter(user=self.request.user)
        return super(BookmarkListView, self).get_context_data(object_list=object_list, **kwargs)


@login_required(login_url='/accounts/login/')
def bookmark_create(request):
    url = request.POST.get('url')
    title = request.POST.get('title')
    new_bookmark = Bookmark()
    validator = URLValidator()
    user = request.user

    try:
        validator(url)  # url 유효성 검사

        # 타이틀 가져오기
        context = ssl._create_unverified_context()
        html = urlopen(url, context=context)
        bs_object = BeautifulSoup(html, "html.parser")

        if not title:
            title = bs_object.find("title").text

        # DB 등록
        new_bookmark.url = url
        new_bookmark.title = title
        new_bookmark.user = user
        new_bookmark.favicon_url = "http://www.google.com/s2/favicons?domain_url=" + url
        new_bookmark.save()

    except ValidationError as exception:
        # URL is NOT valid here.
        print(exception)

    return HttpResponseRedirect(reverse('home'))


@login_required(login_url='/accounts/login/')
def bookmark_delete(request, pk):
    bookmark = Bookmark.objects.get(pk=pk)
    if bookmark.user == request.user:
        bookmark.delete()
        return HttpResponseRedirect(reverse('home'))


@login_required(login_url='/accounts/login/')
def bookmark_update(request, pk):
    url = request.POST.get('url')
    title = request.POST.get('title')
    new_bookmark = Bookmark.objects.get(pk=pk)
    validator = URLValidator()
    user = request.user

    try:
        validator(url)  # url 유효성 검사

        # 타이틀 가져오기
        context = ssl._create_unverified_context()
        html = urlopen(url, context=context)
        bs_object = BeautifulSoup(html, "html.parser")

        if not title:
            title = bs_object.find("title").text

        # DB 등록
        new_bookmark.url = url
        new_bookmark.title = title
        new_bookmark.user = user
        new_bookmark.favicon_url = "http://www.google.com/s2/favicons?domain_url=" + url
        new_bookmark.save()

    except ValidationError as exception:
        # URL is NOT valid here.
        print(exception)

    return HttpResponseRedirect(reverse('home'))

bookmarkapp/templates/bookmarkapp/list.html
{% load bootstrap4 %}
    <div class="bookmark_form_div">
        <h2 class="form_title">bookmarks</h2>

        {% for bookmark in bookmark_list %}
        <div class="bookmark_box">
            <div class="button_div">
                <img src="{{ bookmark.favicon_url }}">
                <a href="{{ bookmark.url }}">{{ bookmark.title | truncatechars:20 }}</a>
                <span>
                    <button class="material-icons edit_button" data-toggle="modal" data-target="#delete_modal{{ bookmark.pk }}" class="material-icons">delete</button>
                    <button class="material-icons edit_button" data-toggle="modal" data-target="#bookmark_update{{ bookmark.pk }}" class="material-icons">edit</button>
                </span>
            </div>
        </div>

        <div id="delete_modal{{ bookmark.pk }}" class="modal fade modal_box_div" role="dialog" data-backdrop="false" style="display: none;">
            <div role="document">
                        <h4>delete bookmark</h4>
                        <hr>
                    <div>
                        Are you sure you want to delete this bookmark?
                    </div>
                    <hr>
                    <div>
                        <button onclick="delete_modal({{ bookmark.pk }})" type="button" class="btn btn-dark">delete</button>
                        <button type="button" class="btn btn-light" data-dismiss="modal" onclick="hideModal('delete_modal({{ bookmark.pk }})')">cancel</button>
                    </div>
            </div>
        </div>

        <div id="bookmark_update{{ bookmark.pk }}" class="modal fade modal_box_div" role="dialog" data-backdrop="false" style="display: none;">
            <div role="document">
                <h4>edit bookmark</h4>
                <hr>
                <form action="{% url 'bookmarkapp:update' pk=bookmark.pk %}" method="post" class="form-inline">
                    {% csrf_token %}
                    <input type="text" id="title" name="title" placeholder="input title" value="{{ bookmark.title }}"><br>
                    <input type="text" id="url" name="url" placeholder="*input url*" value="{{ bookmark.url }}">
                    <hr>
                    <input type="submit" class="btn btn-primary" value="apply">
                    <button type="button" class="btn btn-default" onclick="hideModal('bookmark_update{{ bookmark.pk }}')">cancel</button>
                </form>
            </div>
        </div>
        {% endfor %}

        <div id="bookmark_add" class="modal fade modal_box_div" role="dialog" data-backdrop="false" style="display: none;">
            <div role="document">

                <h4>add new bookmark</h4>
                <hr>

                <form action="{% url 'bookmarkapp:create' %}" method="post" class="form-inline">
                    {% csrf_token %}
                    <input type="text" class="input" name="title" placeholder="input title"><br>
                    <input type="text" class="input" name="url" placeholder="*input url*">
                    <hr>
                    <input type="submit" class="btn btn-primary" value="add">
                    <button type="button" class="btn btn-default" onclick="hideModal('bookmark_add')">cancel</button>
                </form>
            </div>
        </div>

        <button type="button" class="material-icons button_add" data-target="#bookmark_add" data-toggle="modal">add</button>
    </div>



    <script type="text/javascript">
        function delete_modal( pk ) {
            location.replace('/bookmarks/delete/'+pk);
            alert('deleting completed');
        }

        function hideModal( id ) {
            $(id).removeClass("in");
            $(".modal-backdrop").remove();
            $(".show").remove();
            $('body').removeClass('modal-open');
            $('body').css('padding-right', '');
            $(id).hide();
        }
    </script>