BaaN/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accountapp.views import AccountMainView

urlpatterns = [
    path('', AccountMainView.as_view(), name="home"),
    path('summernote/', include('django_summernote.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('bookmarks/', include('bookmarkapp.urls')),
    path('calendars/', include('calendarapp.urls')),
    path('memos/', include('memoapp.urls')),
    path('todos/', include('todoapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todoapp/urls.py
from django.urls import path

from todoapp import views
from todoapp.views import TodoListView, TodoCreateView

app_name = 'todoapp'

urlpatterns = [
    path('list/', TodoListView.as_view(), name='list'),
    path('create/', TodoCreateView.as_view(), name='create'),
    path('update/<int:pk>', views.todo_update, name='update'),
    path('delete/<int:pk>', views.todo_delete, name='delete'),
    path('check/<int:pk>', views.todo_check, name='check'),
    path('delete_all/', views.todo_delete_all, name='delete_all'),
]

todoapp/models.py
from django.contrib.auth.models import User
from django.db import models


# class TodoList(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='todolist', null=False)
#     title = models.CharField(max_length=20, null=True, default="todo list")
#
#     def __str__(self):
#         return self.title


class Todo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='todo', null=True)
    content = models.CharField(max_length=50, null=False)
    done = models.BooleanField(default=False)

    def __str__(self):
        return self.content

todoapp/forms.py
from django import forms
from django.forms import ModelForm
from todoapp.models import Todo


class TodoCreationForm(ModelForm):
    class Meta:
        model = Todo
        fields = ['content']

    content = forms.CharField(
        label="",
        widget=forms.TextInput(attrs={
            "placeholder": "enter your task",
            "class": "account_form_input",
            "style": "margin-bottom: 0rem;"
        })
    )

todoapp/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect

# Create your views here.
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from django.views.generic.edit import FormMixin, CreateView

from todoapp.forms import TodoCreationForm
from todoapp.models import Todo


@method_decorator(login_required(login_url='/accounts/login/'), 'get')
class TodoListView(ListView, FormMixin):
    model = Todo
    form_class = TodoCreationForm
    context_object_name = 'todo_list'
    template_name = 'todoapp/list.html'

    def get_context_data(self, **kwargs):
        object_list = Todo.objects.filter(user=self.request.user).order_by('done')
        return super(TodoListView, self).get_context_data(object_list=object_list, **kwargs)


@method_decorator(login_required(login_url='/accounts/login/'), 'get')
@method_decorator(login_required(login_url='/accounts/login/'), 'post')
class TodoCreateView(CreateView):
    model = Todo
    form_class = TodoCreationForm
    template_name = 'todoapp/create.html'

    def form_valid(self, form):
        temp_todo = form.save(commit=False)
        temp_todo.user = self.request.user
        temp_todo.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('home')


@login_required(login_url='/accounts/login/')
def todo_delete(request, pk):
    todo = Todo.objects.get(pk=pk)
    if todo.user == request.user:
        todo.delete()
        return HttpResponseRedirect(reverse('home'))


@login_required(login_url='/accounts/login/')
def todo_delete_all(request):
    todo_list = Todo.objects.filter(user=request.user)
    for todo in todo_list:
        todo.delete()
    return HttpResponseRedirect(reverse('home'))


@login_required(login_url='/accounts/login/')
def todo_update(request, pk):
    content = request.POST.get('title')
    todo = Todo.objects.get(pk=pk)
    user = request.user

    todo.content = content
    todo.user = user
    todo.save()

    return HttpResponseRedirect(reverse('home'))


@login_required(login_url='/accounts/login/')
def todo_check(request, pk):
    todo = Todo.objects.get(pk=pk)
    todo.done = not todo.done
    todo.save()

    return HttpResponseRedirect(reverse('home'))

todoapp/templates/todoapp/create.html
{% load bootstrap4 %}

{% block content %}
    <div>
        <form action="{% url 'todoapp:create' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="button_add material-icons">add</button>
        </form>
    </div>
{% endblock %}

todoapp/templates/todoapp/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <script type="text/javascript">
        function delete_all() {
            location.replace('/todos/delete_all/');
            alert('deleted all tasks');
        }

        function todo_check( pk ) {
            location.replace('/todos/check/'+pk);
        }

        function hideModal( id ) {
            $(id).removeClass("in");
            $(".modal-backdrop").remove();
            $(".show").remove();
            $('body').removeClass('modal-open');
            $('body').css('padding-right', '');
            $(id).hide();
        }
    </script>

    <div class="bookmark_form_div">
        <h2 class="form_title" style="margin-bottom: 1rem;">todo list&nbsp</h2>
        <div style="vertical-align: bottom; margin-bottom: 2rem;"><a data-target="#delete_all_modal" class="account_url" data-toggle="modal">
            delete all&nbsp<span class="material-icons edit_button">delete_forever</span>
        </a></div>

        {% for todo in todo_list %}

            <div class="button_div">
                {% if todo.done %}
                    <a class="material-icons checked" onclick="todo_check(pk={{ todo.pk }})">
                        check_box
                    </a>
                    <span class="checked" style="color: gray;">{{ todo.content }}</span>
                {% else %}
                    <a class="material-icons unchecked" onclick="todo_check(pk={{ todo.pk }})">
                        check_box_outline_blank
                    </a>
                    <span>{{ todo.content }}</span>
                {% endif %}
                <span>
                    <a data-toggle="modal" data-target="#todo_update{{ todo.pk }}" class="material-icons edit_button">edit</a>
                    <a href="{% url 'todoapp:delete' pk=todo.pk %}" class="material-icons edit_button">delete</a>
                </span>
            </div>

            <div id="delete_all_modal" class="modal fade modal_box_div" tabindex="-1" role="dialog">
                <div role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">delete all tasks</h4>
                            <button type="button" class="close" onclick="hideModal('delete_all_modal')" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>Are you sure you want to delete all task?</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" onclick="delete_all()" class="btn btn-dark">delete</button>
                            <button type="button" class="btn btn-light" data-dismiss="modal">cancel</button>
                        </div>
                    </div>
                </div>
            </div>

            <div id="todo_update{{ todo.pk }}" class="modal fade modal_box_div" role="dialog" data-backdrop="false">
                <div role="document">

                    <h4>edit task</h4>
                    <hr>

                    <form action="{% url 'todoapp:update' pk=todo.pk %}" method="post" class="form-inline">
                        {% csrf_token %}
                        <input type="text" class="" id="new_title" name="title" placeholder="input title" value="{{ todo.content }}"><br>
                        <hr>
                        <input type="submit" id="submit" class=" button_submit" value="apply">
                        <button type="button" class="material-icons" onclick="hideModal('todo_update{{ todo.pk }}')">cancel</button>
                    </form>
                </div>
            </div>

        {% endfor %}

        <hr>

        {% include 'todoapp/create.html' %}

    </div>

{% endblock %}